### ISSUE TITLE
Bar chart disappears when page is resized

### ISSUE THREAD

**Issue by KermitPPI** [mendix/ChartJS#47]
I noticed that my bar chart disappears when the page is resized, the chart is responsive, but instead of adjusting to the size of the screen, the chart disappears completely, is anyone else having any issues with this?

**Comment by pimvdnoll** [comment]
jup same here.

**Comment by KermitPPI** [comment]
Do you know if there has been a fix for this issue @pimvdnoll?  I wasn't sure if this was a problem with the mendix Chartjs widget or the Chartjs library itself.  Thank you.

**Comment by pimvdnoll** [comment]
I see only issues in Chrom in combintion of nested divs. Firefox all good.

**Comment by Mcpoowl** [comment]
I have the same issue, with every type of chart I use. When I look at the developer tools i see it has something to do with the draw method, and a negative radius value.

It should be fixed in the, currently in development, v2.0 version of ChartJS. 
A similar issue is found here at the ChartJS github: nnnick/Chart.js#1057

**Comment by JelteMX** [comment]
Fixed in [v3.0.0](https://github.com/mendix/ChartJS/releases/tag/v3.0.0) release
