### ISSUE TITLE
Feature: the on click microflow is dependent on the position of the click on the canvas

### ISSUE THREAD

**Issue by AlexanderHoltbach** [mendix/ChartJS#66]
It would be nice to have a pie chart for instance and be able to show a page dependent on which piece of the pie you click

**Comment by JelteMX** [comment]
Just made a start @ https://github.com/mendix/ChartJS/tree/feature/onclickposition. Will have to see how we can incorporate it. It will probably require an extra Entity that you will need to set for the Microflow. That Entity will contain, for example, a label or index, that will identify the label or position you clicked.

**Comment by Mcpoowl** [comment]
Since each dataset has a label, can't we let the widget pas the label as a String parameter to the microflow. We could then do a nasty String check in the microflow to determine which page to show (if $stringParameter = 'MyDataSetLabel' ShowPage 1

**Comment by JelteMX** [comment]
Will be available in the AppStore 3.5.0 release, we're still testing. You will now have the possibilty to set a on click DataSet Microflow (which will pass the corresponding DataSet) and/or a on click DataPoint Microflow. The latter is not available in PieChart/DoughnutChart/PolarChart, because they dont have multiseries datasets
